name: Run Python Script Continuously

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.3.12'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run script
        run: python email_sec.py
